// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDftV3knWTDuDdgn8jwu-dxYUWkBjGCQxM',
    appId: '1:160845601284:web:aff9a57741912a10f5b351',
    messagingSenderId: '160845601284',
    projectId: 'borcelle-shoes-store',
    authDomain: 'borcelle-shoes-store.firebaseapp.com',
    storageBucket: 'borcelle-shoes-store.firebasestorage.app',
    measurementId: 'G-MGKVZ1QJKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbWcTu52ADo9htuG1NqfmYAyELzFlpxFk',
    appId: '1:160845601284:android:2935024f71d673aff5b351',
    messagingSenderId: '160845601284',
    projectId: 'borcelle-shoes-store',
    storageBucket: 'borcelle-shoes-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLn92k145THod0rywCHZ_vdDfOlxnv3gI',
    appId: '1:160845601284:ios:24dd85d578006a8bf5b351',
    messagingSenderId: '160845601284',
    projectId: 'borcelle-shoes-store',
    storageBucket: 'borcelle-shoes-store.firebasestorage.app',
    iosBundleId: 'com.example.figmaEcomUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLn92k145THod0rywCHZ_vdDfOlxnv3gI',
    appId: '1:160845601284:ios:24dd85d578006a8bf5b351',
    messagingSenderId: '160845601284',
    projectId: 'borcelle-shoes-store',
    storageBucket: 'borcelle-shoes-store.firebasestorage.app',
    iosBundleId: 'com.example.figmaEcomUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDftV3knWTDuDdgn8jwu-dxYUWkBjGCQxM',
    appId: '1:160845601284:web:c33ec166cbf43a46f5b351',
    messagingSenderId: '160845601284',
    projectId: 'borcelle-shoes-store',
    authDomain: 'borcelle-shoes-store.firebaseapp.com',
    storageBucket: 'borcelle-shoes-store.firebasestorage.app',
    measurementId: 'G-TF1YBP86WH',
  );
}
